---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: argocd-dex-server
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/dexidp/dex:v2.22.0
      importPolicy: {}
      referencePolicy:
        type: Local
