---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: argocd-custom
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/aicoe/argocd:v1.7.4-3
      importPolicy: {}
      referencePolicy:
        type: Local
