---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: redis
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: redis:5.0.8
      importPolicy: {}
      referencePolicy:
        type: Local
