apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        image: argocd-custom
        command:
        - argocd-server
        - --staticassets
        - /shared/app
        - --insecure
