apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../moc-base
  - app-of-apps.yaml

patchesJson6902:
  - target:
      kind: ConfigMap
      name: argocd-cm
      version: v1
    patch: |
      - op: replace
        path: /data/url
        value: https://argocd-server-argocd.apps.moc-infra.massopen.cloud
